version: "3"
services:
  mainchain-validator-devnet-1:
    hostname: mainchain-validator-devnet-1
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: d53c9ed503e4131259afd4f0d70636eed8bb39d23996055acd0cf8fda350cebb
        password: pass
    container_name: mainchain-validator-devnet-1
    command: /root/.go/bin/und --verbosity 4 --datadir /root/.und_mainchain --identity "mainchain-validator-devnet-1" --password /root/.accountpassword --networkid 50009 --port 30401 --mine --gasprice "1" --targetgaslimit "420000000" --etherbase "0x001A320943d4535e93d31E4A65a6e21C5dF375D7" --unlock "0x001A320943d4535e93d31E4A65a6e21C5dF375D7" --syncmode="full" --nodekey="/root/.und_mainchain/bootnode_keys/ev1.txt" --nodiscover
    ports:
      - 30401:30401/tcp
    expose:
      - 30401
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.2

  mainchain-validator-devnet-2:
    hostname: mainchain-validator-devnet-2
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: 794357bf8873d8e61fdbd35c98977077f5ceafb1a20cba79e32b79df77c14271
        password: pass
    container_name: mainchain-validator-devnet-2
    command: /root/.go/bin/und --verbosity 4 --datadir /root/.und_mainchain --identity "mainchain-validator-devnet-2" --password /root/.accountpassword --networkid 50009 --port 30402 --mine --gasprice "1" --targetgaslimit "420000000" --etherbase "0x002A956804bAD8DCad148aBFF71515F9B057F7E0" --unlock "0x002A956804bAD8DCad148aBFF71515F9B057F7E0" --syncmode="full" --nodekey="/root/.und_mainchain/bootnode_keys/ev2.txt" --nodiscover
    ports:
      - 30402:30402/tcp
    expose:
      - 30402
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.3

  mainchain-validator-devnet-3:
    hostname: mainchain-validator-devnet-3
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: b0fb6ce21f0206c08ac33f590a932adac22384ae6e6760f0b8106e5be53cfc8a
        password: pass
    container_name: mainchain-validator-devnet-3
    command: /root/.go/bin/und --verbosity 4 --datadir /root/.und_mainchain --identity "mainchain-validator-devnet-3" --password /root/.accountpassword --networkid 50009 --port 30403 --mine --gasprice "1" --targetgaslimit "420000000" --etherbase "0x003ADc30A6f4DB59d2698e3D3029fd1BA68b6B15" --unlock "0x003ADc30A6f4DB59d2698e3D3029fd1BA68b6B15" --syncmode="full" --nodekey="/root/.und_mainchain/bootnode_keys/ev3.txt" --nodiscover
    ports:
      - 30403:30403/tcp
    expose:
      - 30403
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.4

  mainchain-validator-devnet-4:
    hostname: mainchain-validator-devnet-4
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: 802828fc56b76f465c87fb641bdefc0f6b9690b5648c59a453c351dc300958ff
        password: pass
    container_name: mainchain-validator-devnet-4
    command: /root/.go/bin/und --verbosity 4 --datadir /root/.und_mainchain --identity "mainchain-validator-devnet-4" --password /root/.accountpassword --networkid 50009 --port 30403 --mine --gasprice "1" --targetgaslimit "420000000" --etherbase "0x004A435F1D54aA5cc9FCfA0fEB6B8c4a428bbB93" --unlock "0x004A435F1D54aA5cc9FCfA0fEB6B8c4a428bbB93" --syncmode="full" --nodekey="/root/.und_mainchain/bootnode_keys/ev4.txt" --nodiscover
    ports:
      - 30404:30404/tcp
    expose:
      - 30404
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.5

  mainchain-rpc-devnet:
    hostname: mainchain-rpc-devnet
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: 529664fd320b494e09eff12bcfd41f63b4776ac02ca05f34ae636d451a005ddf
        password: pass
    container_name: mainchain-rpc-devnet
    command: /root/.go/bin/und --verbosity 4 --datadir /root/.und_mainchain --identity "mainchain-rpc-devnet" --networkid 50009 --port 30404 --rpc --rpccorsdomain "*" --rpcaddr 0.0.0.0 --rpcport 8101 --rpcvhosts "*" --ws --wsaddr 0.0.0.0 --wsport 8111 --wsorigins "*" --syncmode="full" --nodiscover
    ports:
      - 30405:30405/tcp
      - 8101:8101/tcp
      - 8111:8111/tcp
    expose:
      - 30405
      - 8101
      - 8111
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.6

networks:
  mainchain_devnet:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
