version: "3"
services:
  ev-2:
    hostname: ev-2
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: 794357bf8873d8e61fdbd35c98977077f5ceafb1a20cba79e32b79df77c14271
        password: pass
    container_name: ev-2
    command: /bin/bash -c '/root/bootstrap-sans-delve.sh;'
    ports:
      - 30402:30402/tcp
    expose:
      - 30402
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.3
    volumes:
      - ${GOPATH}/src:/root/.go/src
    environment:
      - GOPATH=/root/.go
      - DEBUGGER=false
      - DLV_PORT=40001
      - NODE_TYPE=validator
      - IDENTITY=mainchain-validator-devnet-2
      - NETWORK_ID=50009
      - LISTEN_PORT=30402
      - UNLOCK_ADDRESS=0x002A956804bAD8DCad148aBFF71515F9B057F7E0
      - NODE_KEY=ev2.txt
      - LOG_LEVEL=4
      - DEVNET_JSON=true # true: load und-devnet-50009.json. false: use --devnet flag & load default hard coded genesis
      - DATA_DIR=/root/.und_mainchain/unddevnet

  ev-3:
    hostname: ev-3
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: b0fb6ce21f0206c08ac33f590a932adac22384ae6e6760f0b8106e5be53cfc8a
        password: pass
    container_name: ev-3
    command: /bin/bash -c '/root/bootstrap-sans-delve.sh;'
    ports:
      - 30403:30403/tcp
    expose:
      - 30403
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.4
    volumes:
      - ${GOPATH}/src:/root/.go/src
    environment:
      - GOPATH=/root/.go
      - DEBUGGER=false
      - DLV_PORT=40002
      - NODE_TYPE=validator
      - IDENTITY=mainchain-validator-devnet-3
      - NETWORK_ID=50009
      - LISTEN_PORT=30403
      - UNLOCK_ADDRESS=0x003ADc30A6f4DB59d2698e3D3029fd1BA68b6B15
      - NODE_KEY=ev3.txt
      - LOG_LEVEL=4
      - DEVNET_JSON=true
      - DATA_DIR=/root/.und_mainchain/unddevnet

  ev-4:
    hostname: ev-4
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: 802828fc56b76f465c87fb641bdefc0f6b9690b5648c59a453c351dc300958ff
        password: pass
    container_name: ev-4
    command: /bin/bash -c '/root/bootstrap-sans-delve.sh;'
    ports:
      - 30404:30404/tcp
    expose:
      - 30404
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.5
    volumes:
      - ${GOPATH}/src:/root/.go/src
    environment:
      - GOPATH=/root/.go
      - DEBUGGER=false
      - DLV_PORT=40002
      - NODE_TYPE=validator
      - IDENTITY=mainchain-validator-devnet-4
      - NETWORK_ID=50009
      - LISTEN_PORT=30404
      - UNLOCK_ADDRESS=0x004A435F1D54aA5cc9FCfA0fEB6B8c4a428bbB93
      - NODE_KEY=ev4.txt
      - LOG_LEVEL=4
      - DEVNET_JSON=true
      - DATA_DIR=/root/.und_mainchain/unddevnet

networks:
  mainchain_devnet:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
