version: "3"
services:
  mainchain-validator-devnet-1:
    hostname: mainchain-validator-devnet-1
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: d53c9ed503e4131259afd4f0d70636eed8bb39d23996055acd0cf8fda350cebb
        password: pass
    container_name: mainchain-validator-devnet-1
    security_opt:
      - seccomp:unconfined # required if running through delve, i.e. DEBUGGER == true
    command: /bin/bash -c '/root/bootstrap.sh;'
    ports:
      - 30401:30401/tcp
      - 40000:40000
    expose:
      - 30401
      - 40000
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.2
    volumes:
      - ${GOPATH}/src:/root/.go/src
    environment:
      - GOPATH=/root/.go
      - DEBUGGER=true
      - DLV_PORT=40000
      - NODE_TYPE=validator
      - IDENTITY=mainchain-validator-devnet-1
      - NETWORK_ID=50009
      - LISTEN_PORT=30401
      - UNLOCK_ADDRESS=0x001A320943d4535e93d31E4A65a6e21C5dF375D7
      - NODE_KEY=ev1.txt
      - LOG_LEVEL=9
      - DEVNET_JSON=true # true: load und-devnet-50009.json. false: use --devnet flag & load default hard coded genesis
      - DATA_DIR=/root/.und_mainchain/unddevnet

  mainchain-validator-devnet-2:
    hostname: mainchain-validator-devnet-2
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: 794357bf8873d8e61fdbd35c98977077f5ceafb1a20cba79e32b79df77c14271
        password: pass
    container_name: mainchain-validator-devnet-2
    command: /bin/bash -c '/root/bootstrap.sh;'
    ports:
      - 30402:30402/tcp
      - 40001:40001
    expose:
      - 30402
      - 40001
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.3
    volumes:
      - ${GOPATH}/src:/root/.go/src
    environment:
      - GOPATH=/root/.go
      - DEBUGGER=false
      - DLV_PORT=40001
      - NODE_TYPE=validator
      - IDENTITY=mainchain-validator-devnet-2
      - NETWORK_ID=50009
      - LISTEN_PORT=30402
      - UNLOCK_ADDRESS=0x002A956804bAD8DCad148aBFF71515F9B057F7E0
      - NODE_KEY=ev2.txt
      - LOG_LEVEL=4
      - DEVNET_JSON=true
      - DATA_DIR=/root/.und_mainchain/unddevnet

  mainchain-validator-devnet-3:
    hostname: mainchain-validator-devnet-3
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: b0fb6ce21f0206c08ac33f590a932adac22384ae6e6760f0b8106e5be53cfc8a
        password: pass
    container_name: mainchain-validator-devnet-3
    command: /bin/bash -c '/root/bootstrap.sh;'
    ports:
      - 30403:30403/tcp
      - 40002:40002
    expose:
      - 30403
      - 40002
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.4
    volumes:
      - ${GOPATH}/src:/root/.go/src
    environment:
      - GOPATH=/root/.go
      - DEBUGGER=false
      - DLV_PORT=40002
      - NODE_TYPE=validator
      - IDENTITY=mainchain-validator-devnet-3
      - NETWORK_ID=50009
      - LISTEN_PORT=30403
      - UNLOCK_ADDRESS=0x003ADc30A6f4DB59d2698e3D3029fd1BA68b6B15
      - NODE_KEY=ev3.txt
      - LOG_LEVEL=4
      - DEVNET_JSON=true
      - DATA_DIR=/root/.und_mainchain/unddevnet

  mainchain-validator-devnet-4:
    hostname: mainchain-validator-devnet-4
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: 802828fc56b76f465c87fb641bdefc0f6b9690b5648c59a453c351dc300958ff
        password: pass
    container_name: mainchain-validator-devnet-4
    command: /bin/bash -c '/root/bootstrap.sh;'
    ports:
      - 30404:30404/tcp
      - 40003:40003
    expose:
      - 30404
      - 40003
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.5
    volumes:
      - ${GOPATH}/src:/root/.go/src
    environment:
      - GOPATH=/root/.go
      - DEBUGGER=false
      - DLV_PORT=40003
      - NODE_TYPE=validator
      - IDENTITY=mainchain-validator-devnet-4
      - NETWORK_ID=50009
      - LISTEN_PORT=30404
      - UNLOCK_ADDRESS=0x004A435F1D54aA5cc9FCfA0fEB6B8c4a428bbB93
      - NODE_KEY=ev4.txt
      - LOG_LEVEL=4
      - DEVNET_JSON=true
      - DATA_DIR=/root/.und_mainchain/unddevnet

  mainchain-rpc-devnet:
    hostname: mainchain-rpc-devnet
    build:
      context: ../
      dockerfile: ./docker/validator/Dockerfile
      args:
        privatekey: 529664fd320b494e09eff12bcfd41f63b4776ac02ca05f34ae636d451a005ddf
        password: pass
    container_name: mainchain-rpc-devnet
    command: /bin/bash -c '/root/bootstrap.sh;'
    ports:
      - 30405:30405/tcp
      - 8101:8101/tcp
      - 8111:8111/tcp
      - 40004:40004
    expose:
      - 30405
      - 8101
      - 8111
      - 40004
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.6
    volumes:
      - ${GOPATH}/src:/root/.go/src
    environment:
      - GOPATH=/root/.go
      - DEBUGGER=false
      - DLV_PORT=40004
      - NODE_TYPE=rpc
      - IDENTITY=mainchain-rpc-devnet
      - NETWORK_ID=50009
      - LISTEN_PORT=30405
      - UNLOCK_ADDRESS=
      - NODE_KEY=
      - LOG_LEVEL=4
      - DEVNET_JSON=true
      - DATA_DIR=/root/.und_mainchain/unddevnet

networks:
  mainchain_devnet:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
